### ISSUE TITLE
feat: unfold json with intermediate level

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/posimap#34]
Schema definition

```yaml
  - name: DATE
    length: 8
    schema:
      - name: SS
        length: 2
      - name: AAMMJJ
        length: 6
```

Should accept both JSON to unfold

```json
{"DATE": "20250201"}
```

```json
{"DATE": {"SS": "20", "AAMMJJ": "250201"}}
```
